import type { Metadata } from 'next';
import './globals.css';
import { AppProvider } from '@/context/AppContext';
import TransitionWrapper from './TransitionWrapper';
import { Roboto } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={roboto.className}>
        <TransitionWrapper>
          <AppProvider>{children}</AppProvider>
        </TransitionWrapper>
      </body>
    </html>
  );
}
