import type { Metadata } from 'next';
import './styles/mantineBase.css';
import './globals.scss';
import '@mantine/core/styles.css';
import '@splidejs/react-splide/css';
import { AppProvider } from '@/context/AppContext';
import TransitionWrapper from './TransitionWrapper';
import { Roboto } from 'next/font/google';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={roboto.className}>
        <TransitionWrapper>
          <AppProvider>
            <MantineProvider >{children}</MantineProvider>
          </AppProvider>
        </TransitionWrapper>
      </body>
    </html>
  );
}
